name: Lint

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Lint JavaScript
              run: npm run lint:js

            - name: Lint CSS
              run: npm run lint:css

    lint-php:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer

            - name: Install dependencies
              run: composer install --no-progress --prefer-dist

            - name: Lint PHP
              run: vendor/bin/phpcs
